kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mongo-storage-class  
  namespace: default
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: managed