apiVersion: apps/v1
kind: Deployment
metadata:
  name: gts-userdata-dyqh-service
  namespace: spring-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gts-userdata-dyqh-service
  template:
    metadata:
      labels:
        app: gts-userdata-dyqh-service
    spec:
      containers:
      - name: gts-userdata-dyqh-service
        image: gangtiseacr.azurecr.cn/gts-userdata-dyqh-service:1.0.0
        resources:
          requests:
            cpu: 250m
            memory: 960Mi
          limits:
            cpu: 250m
            memory: 960Mi
        ports:
        - containerPort: 12002
        envFrom:
        - configMapRef:
            name: spring-config
        env:
          - name: KAFKA_GROUP_ID
            value: userdataEAGroup
          - name: MONGODB_URI
            value: mongodb://gangtise:5kGYjDURA1tboaY5lih53kJ5mU0ZQVJkfJ183jIMofrbDmtyF4JFXtmjsDWrMNd7UPR5pEaCnOzH54Un6tpW2g==@gangtise.mongo.cosmos.azure.cn:10255/user_data?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@gangtise@
        #nfs
        volumeMounts:
          - mountPath: /export/home/log
            name: nfsk8s
      volumes:
        - name: nfsk8s
          persistentVolumeClaim:
            claimName: nfsk8s        
---
apiVersion: v1
kind: Service
metadata:
  name: gts-userdata-dyqh-service
  namespace: spring-app
spec:
  ports:
  - port: 12002
  selector:
    app: gts-userdata-dyqh-service