---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
    kubesphere.io/alias-name: gangtise-user-web
    kubesphere.io/maxSurgePod: '2'
    kubesphere.io/minAvailablePod: '1'
  creationTimestamp: '2020-06-30T07:13:16Z'
  generation: 2
  labels:
    app: gangtise-user-web
  name: gangtise-user-web
  namespace: spring-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gangtise-user-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubesphere.io/containerSecrets: '{"container-nwbair":"azure-acr"}'
      creationTimestamp: null
      labels:
        app: gangtise-user-web
    spec:
      affinity: {}
      containers:
        - image: 'gangtiseacr.azurecr.cn/gangtise-user-web:1.0.1'
          imagePullPolicy: IfNotPresent
          name: container-nwbair
          ports:
            - containerPort: 9528
              name: http-userweb
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 10m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: azure-acr
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30

