apiVersion: apps/v1
kind: Deployment
metadata:
  name: gangtise-auth-service
  namespace: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gangtise-auth-service
  template:
    metadata:
      labels:
        app: gangtise-auth-service
    spec:
      containers:
      - name: gangtise-auth-service
        image: gangtiseacr.azurecr.cn/gangtise-auth-service
        resources:
          requests:
            cpu: 250m
            memory: 960Mi
          limits:
            cpu: 250m
            memory: 960Mi
        ports:
        - containerPort: 10010
        envFrom:
        - configMapRef:
            name: spring-config

---
apiVersion: v1
kind: Service
metadata:
  name: gangtise-auth-service
  namespace: spring-app
spec:
  ports:
  - port: 10010
  selector:
    app: gangtise-auth-service