apiVersion: apps/v1
kind: Deployment
metadata:
  name: gts-info-service
  namespace: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gts-info-service
  template:
    metadata:
      labels:
        app: gts-info-service
    spec:
      containers:
      - name: gts-info-service
        image: gangtiseacr.azurecr.cn/gts-info-service:1.0.0
        resources:
          requests:
            cpu: 200m
            memory: 800Mi
          limits:
            cpu: 200m
            memory: 800Mi
        ports:
        - containerPort: 10049
        envFrom:
        - configMapRef:
            name: spring-config
        env:
          - name: MYSQL_URL
            value: jdbc:mysql://gangtisedb.mysql.database.chinacloudapi.cn:3306/gangtise_info?useSSL=true&requireSSL=false&characterEncoding=UTF-8
          - name: MYSQL_USERNAME
            value: gangtise@gangtisedb
          - name: MYSQL_PASSWORD
            value: Qwer!234

---
apiVersion: v1
kind: Service
metadata:
  name: gts-info-service
  namespace: spring-app
spec:
  ports:
  - port: 10049
  selector:
    app: gts-info-service