apiVersion: apps/v1
kind: Deployment
metadata:
  name: gts-dataconvert-service2
  namespace: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gts-dataconvert-service2
  template:
    metadata:
      labels:
        app: gts-dataconvert-service2
    spec:
      hostAliases:
        - hostnames:
            - cdh1
          ip: 10.0.3.4
        - hostnames:
            - cdh2
          ip: 10.0.3.5
        - hostnames:
            - cdh3
          ip: 10.0.3.9
        - hostnames:
            - cdh4
          ip: 10.0.3.10
      containers:
      - name: gts-dataconvert-service2
        image: gangtiseacr.azurecr.cn/gts-dataconvert-service2:1.0.0
        resources:
          requests:
            cpu: 200m
            memory: 960Mi
          limits:
            cpu: 1000m
            memory: 960Mi
        ports:
        - containerPort: 10033
        envFrom:
        - configMapRef:
            name: spring-config
        env:
          - name: KAFKA_GROUP_ID
            value: cdm_dataconvert
          - name: CDM_JYDB_TOPIC
            value: cdm_139.217.219.124_jydb
          - name: MYSQL_URL
            value: jdbc:mysql://gangtisedb.mysql.database.chinacloudapi.cn:3306/cdm_gangtise_db?useSSL=true&requireSSL=false&characterEncoding=UTF-8
          - name: MYSQL_USERNAME
            value: gangtise@gangtisedb
          - name: MYSQL_PASSWORD
            value: Qwer!234
         
---
apiVersion: v1
kind: Service
metadata:
  name: gts-dataconvert-service2
  namespace: spring-app
spec:
  ports:
  - port: 10033
  selector:
    app: gts-dataconvert-service2