apiVersion: apps/v1
kind: Deployment
metadata:
  name: gts-keyboard-common-search
  namespace: spring-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gts-keyboard-common-search
  template:
    metadata:
      labels:
        app: gts-keyboard-common-search
    spec:
      containers:
      - name: gts-keyboard-common-search
        image: gangtiseacr.azurecr.cn/gts-keyboard-common-search:1.0.0
        resources:
          requests:
            cpu: 250m
            memory: 960Mi
          limits:
            cpu: 250m
            memory: 960Mi
        ports:
        - containerPort: 13011
        envFrom:
        - configMapRef:
            name: spring-config
        env:
          - name: ES_CLUSTER_NAME
            value: elasticsearch
          - name: ES_NODES
            value: 10.0.2.10:9300,10.0.2.11:9300,10.0.2.12:9300

---
apiVersion: v1
kind: Service
metadata:
  name: gts-keyboard-common-search
  namespace: spring-app
spec:
  ports:
  - port: 13011
  selector:
    app: gts-keyboard-common-search