apiVersion: apps/v1
kind: Deployment
metadata:
  name: gangtise-gateway-service
  namespace: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gangtise-gateway-service
  template:
    metadata:
      labels:
        app: gangtise-gateway-service
    spec:
      containers:
      - name: gangtise-gateway-service
        image: gangtiseacr.azurecr.cn/gangtise-gateway-service
        resources:
          requests:
            cpu: 250m
            memory: 960Mi
          limits:
            cpu: 250m
            memory: 960Mi
        ports:
        - containerPort: 1925
        envFrom:
        - configMapRef:
            name: spring-config

