apiVersion: apps/v1
kind: Deployment
metadata:
  name: gangtise-gateway-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gangtise-gateway-service
  template:
    metadata:
      labels:
        app: gangtise-gateway-service
    spec:
      containers:
      - name: gangtise-gateway-service
        image: gangcloudapp.azurecr.cn/gangtise-gateway-service
        resources:
          requests:
            cpu: 250m
            memory: 960Mi
          limits:
            cpu: 250m
            memory: 960Mi
        ports:
        - containerPort: 1925

---
apiVersion: v1
kind: Service
metadata:
  name: gangtise-gateway-service
spec:
  type: LoadBalancer
  ports:
    - port: 1925
  selector:
    app: gangtise-gateway-service