apiVersion: v1
kind: Service
metadata:
  name: gangtise-gateway-service
  namespace: spring-app
spec:
  type: LoadBalancer
  ports:
    - port: 1925
      name: gangtise-gateway-service
  selector:
    app: gangtise-gateway-service