apiVersion: v1
kind: Service
metadata:
  name: gangtise-userinfo-service
  namespace: spring-app
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 120.240.0.223
  ports:
  - port: 10030
  selector:
    app: gangtise-userinfo-service