apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway
  namespace: spring-app
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 120.240.0.190
  ports:
    - port: 1925
      name: gangtise-gateway-service
  selector:
    app: gangtise-gateway-service