apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsk8s
  labels:
    type: nfs
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: gts-nfs
  nfs:
    server: 172.18.1.4
    path: /data