apiVersion: v1
data:
  redis.conf: |
    appendonly yes
    cluster-enabled yes
    cluster-config-file /var/lib/redis/nodes.conf
    cluster-node-timeout 5000
    dir /var/lib/redis
    port 6379
kind: ConfigMap
metadata:
  creationTimestamp: '2021-04-08T01:24:54Z'
  name: redis-conf
  namespace: default
  resourceVersion: '283327'
  selfLink: /api/v1/namespaces/default/configmaps/redis-conf
  uid: 2e63bf57-2840-499b-94a2-64b2e604d0f1