apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: NodePort
  ports:
  - name: redis-port
    port: 6379
    targetPort: 6379
    nodePort: 30379
  selector:
    app: redis
    appCluster: redis-cluster