apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
  namespace: spring-app-visitor
spec:
  serviceName: eureka
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: gangtiseacr.azurecr.cn/gangtise-eureka-service:1.0.0
          ports:
            - containerPort: 1025
          resources:
            limits:
              memory: 960Mi
          envFrom:
          - configMapRef:
              name: spring-config-visitor
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: EUREKA_INSTANCE_HOSTNAME
              value: ${MY_POD_NAME}.eureka
  podManagementPolicy: "Parallel"
--- 
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: spring-app-visitor
  labels:
    app: eureka
spec: 
  type: LoadBalancer
  ports:
    - port: 1025
      name: eureka
  selector:
    app: eureka
