apiVersion: apps/v1
kind: Deployment
metadata:
  name: gangtise-userinfo-service
  namespace: spring-app-visitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gangtise-userinfo-service
  template:
    metadata:
      labels:
        app: gangtise-userinfo-service
    spec:
      containers:
      - name: gangtise-userinfo-service
        image: gangtiseacr.azurecr.cn/gangtise-userinfo-service:1.0.0-beta
        resources:
          requests:
            cpu: 250m
            memory: 960Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        ports:
        - containerPort: 10030
        envFrom:
        - configMapRef:
            name: spring-config-visitor
        env:
          - name: AZBLOB_ACCOUNTNAME
            value: gangtisestorage
          - name: AZBLOB_KEY
            value: kDJnXJ/bjj+ky/krihEE9lLFSJgWrBQs46toNjOP9y5H6szXtF8HIhF/1ytYB/tJ9C1iap+gc3Ev23S4XMotuw==          
          - name: AZBLOB_IMAGE
            value: images
          - name: MYSQL_URL
            value: jdbc:mysql://gangtisedb.mysql.database.chinacloudapi.cn:3306/gangtise_visitor?useSSL=true&requireSSL=false&characterEncoding=UTF-8
          - name: MYSQL_USERNAME
            value: gangtise@gangtisedb
          - name: MYSQL_PASSWORD
            value: Qwer!234

            
---
apiVersion: v1
kind: Service
metadata:
  name: gangtise-userinfo-service
  namespace: spring-app-visitor
spec:
  ports:
  - port: 10030
  selector:
    app: gangtise-userinfo-service